export const Paths = {
	login: "/login",
	register: "/register",
	mypage: "/",
	editProfile: "/profile/edit",
	reservation: "/reservation",
	dashboard: "/dashboard",
	selectionInfo: "/selection/information",
	createSelInfo: "/selection/CreateSelInfo/:id",
	selectionSolution: "/selection/solution",
	showEvent: "/events/:id",
	showEs: "/es/:id",
	eventHistory: "/events/history",
	showCaseStudy: "/case/studies/:id",
	comments: "/case/comments/:id",
	caseStudyHistory: "/case/studies/history",
	caseStudyEditHistory: "/case/studies/edithistory",
	esHistory: "/es/history",
	caseStudyCorrection: "/case/studies/correction",
	showCompany: "/companies/:id",
	showMentor: "/mentors/:id",
	entrySheetCorrection: "/entry/sheets/correction/:id",
	ticketPurchase: "/tickets/purchase",
	showArticle: "/articles/:id",
	eSCaseStudy: "/entry/sheets/register",
	createCompanyReview:"/companies/:id/review",
	calandar: "/reservation/calandar",
	
	// admin path
	adminLogin: "/admin/login",
	adminDashboard: "/admin/dashboard",
	adminMentees: "/admin/mentee/list",
	adminTicketHistory: "/admin/ticket/history",
	adminEditMentee: "/admin/mentee/edit/:id",
	adminRegisterMentee: "/admin/mentee/register",
	adminMentors: "/admin/mentor/list",
	adminEditMentor: "/admin/mentor/edit/:id",
	adminRegisterMentor: "/admin/mentor/register",
	adminEvents: "/admin/event/list",
	adminEditEvent: "/admin/event/edit/:id",
	adminCreateEvent: "/admin/event/create",
	adminCaseStudies: "/admin/case/study/list",
	adminEditCaseStudy: "/admin/case/study/edit/:id",
	adminCreateCaseStudy: "/admin/case/study/register",	
	adminCorrectionCaseStudy: "/admin/case/study/correction/:id",
	// adminCaseStudyCorrection: "/admin/case/studies/correction",
	adminEntrySheets: "/admin/entry/sheet/list",
	adminCorrectionEntrySheet: "/admin/entry/sheet/correction/:id",
	adminCompanies: "/admin/company/list",
	adminEditCompany: "/admin/company/edit/:id",
	adminCreateCompany: "/admin/company/create",
	adminIndustries: "/admin/industry/list",
	adminEditIndustry: "/admin/industry/edit/:id",
	adminCreateIndustry: "/admin/industry/create",
	adminArticles: "/admin/article/list",
	adminEditArticle: "/admin/article/edit/:id",
	adminCreateArticle: "/admin/article/create",
	// 2024-01-11 06:20:00 Added by Fatty
	adminSIs: "/admin/selectioninfo/list",
	adminCreateSI: "/admin/selectioninfo/create",
	adminEditSI: "/admin/selectioninfo/edit/:id",
	// 2024-01-11 06:20:00 Added by Fatty
	adminZooms: "/admin/zooms/list",
	adminCreateZooms: "/admin/zooms/create",
	adminEditZooms: "/admin/zooms/edit/:id",
}